### PR TITLE
change most fonts to Roboto Slab

### PR DESCRIPTION
**Pull request by cschweikert**
- Switch ususal text to "Roboto Slab"
- Keep sans-serif font for buttons and the donation pill

grafik

RFC

### CODE REVIEW

**Comment by cschweikert** [comment]
Hm, maybe the menu should also be switched to the new font even though it is based on buttons

**Review by ManuelFeller — APPROVED** [review]
Looks good, code too. Go ahead, will publish tomorrow 👍🎉

**Comment by ManuelFeller** [comment]
> Hm, maybe the menu should also be switched to the new font even though it is based on buttons

We can check that tomorrow - or just go for it, I trust you that you can decide if it looks good or not - advantage would be the same ~~font- centering~~ line height (or however that is called what I have in my wired mind right now) I guess

**Comment by cschweikert** [comment]
grafik

**Pull request merged**
